# Generated by Django 4.0.6 on 2022-07-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=100)),
                ('alt_phone_number', models.CharField(max_length=50)),
                ('man_number', models.CharField(max_length=100)),
                ('employee_number', models.CharField(max_length=100)),
                ('nrc_number', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('work_ministry', models.CharField(max_length=100)),
                ('work_department', models.CharField(max_length=100)),
                ('work_address', models.CharField(max_length=100)),
                ('loan_amount', models.FloatField(default=500.0)),
                ('months_to_repay', models.IntegerField()),
                ('payslip_pdf', models.FileField(upload_to='payslips')),
                ('nrc_pdf', models.FileField(upload_to='nrc')),
            ],
        ),
    ]
