# Generated by Django 4.0.6 on 2022-09-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ekas', '0006_loanapplication_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='nrc_pdf',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='payslip_pdf',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='bank_statement_upload',
            field=models.FileField(blank=True, null=True, upload_to='Bank Statements', verbose_name='Upload Bank Statement. Supported formats: pdf, PNG, JPEG, JPG'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='nrc_upload',
            field=models.FileField(default='aa.jpeg', help_text='Scanned Copy of your NRC. Supported formats: pdf, PNG, JPEG, JPG', upload_to='nrc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='payslip_upload',
            field=models.FileField(default='aa.jpeg', help_text='Your latest payslip. Supported formats: pdf, JPG, PNG, DOCX, JPEG', upload_to='payslips'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='signature',
            field=models.FileField(default='aa.jpeg', help_text='Supported formats: pdf, PNG, JPEG, JPG', upload_to='signatures', verbose_name='Upload Your Signature'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='account_name',
            field=models.CharField(help_text='Bank Account Name as it appears at the Bank', max_length=100),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Is the Application approved?'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='employee_number',
            field=models.CharField(blank=True, help_text='Check your payslip for Employee Number', max_length=100, null=True, verbose_name='Employee Number (Optional)'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_amount',
            field=models.FloatField(choices=[(1000, 1000), (2000, 2000), (3000, 3000), (4000, 4000), (5000, 5000), (6000, 6000), (7000, 7000), (8000, 8000), (9000, 9000), (10000, 10000)], default=1000, help_text='The Amount in Kwacha that you wish to get'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='man_number',
            field=models.CharField(help_text='Check your payslip for your Man Number', max_length=100),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='months_to_repay',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50'), ('51', '51'), ('52', '52'), ('53', '53'), ('54', '54'), ('55', '55'), ('56', '56'), ('57', '57'), ('58', '58'), ('59', '59'), ('60', '60')], default='1', help_text='Number of Months you wish to repay the borrowed amount', max_length=100),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='work_department',
            field=models.CharField(help_text='The department under the selected government ministry', max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='work_ministry',
            field=models.CharField(choices=[('Ministry Of Information and Media', 'Ministry Of Information and Media'), ('Ministry Of Education', 'Ministry Of Education'), ('Ministry Of Home Affairs', 'Ministry Of Home Affairs'), ('Ministry Of Foreign Affairs', 'Ministry Of Foreign Affairs'), ('Ministry Of Foreign Affairs', 'Ministry Of Foreign Affairs'), ('Ministry Of Technology & Science', 'Ministry Of Technology & Science'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Green Economy and Environment', 'Green Economy and Environment'), ('Ministry Of Mines and Minerals Development', 'Ministry Of Mines and Minerals Development'), ('Ministry Of Commerce, Trade and Industry', 'Ministry Of Commerce, Trade and Industry'), ('Ministry Of Transport and Logistics', 'Ministry Of Transport and Logistics'), ('Ministry Of Agriculture', 'Ministry Of Agriculture'), ('Ministry Of Health', 'Ministry Of'), ('Ministry Of Justice', 'Ministry Of Justice'), ('Ministry Of  Water Development and Sanitation', 'Ministry Of  Water Development and Sanitation'), ('Ministry Of Youth, Sport and Arts', 'Ministry Of Youth, Sport and Arts'), ('Ministry Of Lands and Natural Resources', 'Ministry Of Lands and Natural Resources'), ('Ministry Of Labour And Social Security', 'Ministry Of Labour And Social Security'), ('Ministry Of Tourism', 'Ministry Of Tourism'), ('Ministry Of Local Government and Rural Development', 'Ministry Of Local Government and Rural Development'), ('Ministry Of Finance and National Planning', 'Ministry Of Finance and National Planning'), ('Ministry Of Fisheries and Livestock', 'Ministry Of Fisheries and Livestock'), ('Ministry Of Energy', 'Ministry Of Energy'), ('Ministry Of Community Development and Social Services', 'Ministry Of Community Development and Social Services'), ('Ministry Of Infrastructure, Housing Urban and Development', 'Ministry Of Infrastructure, Housing Urban and Development'), ('Ministry Of Small and Medium Enterprises Development', 'Ministry Of Small and Medium Enterprises Development')], max_length=100, verbose_name='Ministry'),
        ),
    ]
