# Generated by Django 4.0.6 on 2022-09-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ekas', '0007_remove_loanapplication_nrc_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_amount',
            field=models.FloatField(choices=[(1000, 1000), (2000, 2000), (3000, 3000), (4000, 4000), (5000, 5000), (6000, 6000), (7000, 7000), (8000, 8000), (9000, 9000), (10000, 10000)], help_text='The Amount in Kwacha that you wish to get'),
        ),
    ]
