# Generated by Django 4.0.6 on 2022-09-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ekas', '0008_alter_loanapplication_loan_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='work_ministry',
            field=models.CharField(choices=[('Ministry Of Information and Media', 'Ministry Of Information and Media'), ('Ministry Of Education', 'Ministry Of Education'), ('Ministry Of Home Affairs', 'Ministry Of Home Affairs'), ('Ministry Of Foreign Affairs', 'Ministry Of Foreign Affairs'), ('Ministry Of Health', 'Ministry Of Health'), ('Ministry Of Technology & Science', 'Ministry Of Technology & Science'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Green Economy and Environment', 'Green Economy and Environment'), ('Ministry Of Mines and Minerals Development', 'Ministry Of Mines and Minerals Development'), ('Ministry Of Commerce, Trade and Industry', 'Ministry Of Commerce, Trade and Industry'), ('Ministry Of Transport and Logistics', 'Ministry Of Transport and Logistics'), ('Ministry Of Agriculture', 'Ministry Of Agriculture'), ('Ministry Of Health', 'Ministry Of'), ('Ministry Of Justice', 'Ministry Of Justice'), ('Ministry Of  Water Development and Sanitation', 'Ministry Of  Water Development and Sanitation'), ('Ministry Of Youth, Sport and Arts', 'Ministry Of Youth, Sport and Arts'), ('Ministry Of Lands and Natural Resources', 'Ministry Of Lands and Natural Resources'), ('Ministry Of Labour And Social Security', 'Ministry Of Labour And Social Security'), ('Ministry Of Tourism', 'Ministry Of Tourism'), ('Ministry Of Local Government and Rural Development', 'Ministry Of Local Government and Rural Development'), ('Ministry Of Finance and National Planning', 'Ministry Of Finance and National Planning'), ('Ministry Of Fisheries and Livestock', 'Ministry Of Fisheries and Livestock'), ('Ministry Of Energy', 'Ministry Of Energy'), ('Ministry Of Community Development and Social Services', 'Ministry Of Community Development and Social Services'), ('Ministry Of Infrastructure, Housing Urban and Development', 'Ministry Of Infrastructure, Housing Urban and Development'), ('Ministry Of Small and Medium Enterprises Development', 'Ministry Of Small and Medium Enterprises Development'), ('Other', 'Other')], max_length=100, verbose_name='Ministry'),
        ),
    ]
